services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 7007:8090
    volumes:
      - /mnt/docker/beszel/:/beszel_data
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true