--- # Fail2ban
- hosts: httpd
  tasks:
  - name: install fail2ban
    yum:
      name: fail2ban
      state: latest
  - name: start fail2ban
    service:
      name: fail2ban
      state: started
  - name: enable fail2ban at boot
    service:
      name: fail2ban
      enabled: yes
