---
- hosts: all
  become: true
  vars:
    new_user: bl
    timezone: America/New_York
  tasks:
    - name: Create bl user
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'

    - name: Download authorized_keys
      get_url:
        url: https://raw.githubusercontent.com/blurer/dotfiles/refs/heads/main/ssh/authorized_keys
        dest: "/home/{{ new_user }}/.ssh/authorized_keys"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0600'

    - name: Install packages
      apt:
        name: [htop, vim, git, curl]
        state: present
        update_cache: yes

    - name: Generate SSH key
      user:
        name: "{{ new_user }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_comment: bl-dev
        force: no
      become_user: "{{ new_user }}"

    - name: Download dotfiles
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0644'
      loop:
        - { url: 'https://raw.githubusercontent.com/blurer/dotfiles/refs/heads/main/editors/.vimrc', dest: '/home/{{ new_user }}/.vimrc' }
        - { url: 'https://raw.githubusercontent.com/blurer/dotfiles/refs/heads/main/shell/.bashrc', dest: '/home/{{ new_user }}/.bashrc' }

    - name: Allow passwordless sudo for bl user
     lineinfile:
       path: /etc/sudoers.d/bl
       line: "bl ALL=(ALL) NOPASSWD:ALL"
       state: present
       mode: '0440'
       create: yes
       validate: 'visudo -cf %s'

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted