---
- hosts: all
  become: true
  tasks:
    - name: set dns servers in resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        backup: yes