---
- hosts: all
  become: true
  tasks:
    - name: set dns servers in resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.2.2.101
          nameserver 10.2.2.100
        backup: yes