--- # Webserver
- hosts: httpd
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add content
    lineinfile:
      line: "here is text"
      path: /var/www/html/index.html
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: enable httpd at boot
    service:
      name: httpd
      enabled: yes
